"""
Core domain models for MarketSensing platform.

Shared data structures used across ingestion, features, ML, and API layers.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import uuid4

import numpy as np


class SignalAction(str, Enum):
    """Signal action type."""
    ENTER = "enter"
    EXIT = "exit"


class SignalSide(str, Enum):
    """Signal direction."""
    BUY = "long"
    SELL = "short"


class SignalState(str, Enum):
    """Signal classification."""
    BUY = "buy"
    SELL = "sell"
    NEUTRAL = "neutral"


@dataclass
class Instrument:
    """Tradeable instrument definition."""
    id: str
    name: str
    exchange: Optional[str] = None
    product_code: Optional[str] = None
    contract_size: Optional[float] = None
    tick_size: Optional[float] = None
    currency: str = "USD"
    category: str = "crude"
    unit: Optional[str] = None


@dataclass
class Signal:
    """Trading signal generated by ML models."""
    signal_id: str = field(default_factory=lambda: str(uuid4()))
    timestamp: datetime = field(default_factory=datetime.utcnow)
    strategy_id: str = ""
    instrument_long: str = ""
    instrument_short: str = ""
    action: SignalAction = SignalAction.ENTER
    side: SignalSide = SignalSide.BUY
    predicted_state: SignalState = SignalState.NEUTRAL
    size: float = 0.0
    confidence: float = 0.0
    expected_hold_time: str = "3d"
    rationale: str = ""
    model_version: str = ""
    risk_checks_passed: bool = True
    predicted_spread: Optional[float] = None
    predicted_margin: Optional[float] = None
    leap_duration_days: Optional[int] = None
    entry_price: Optional[float] = None
    settle_price: Optional[float] = None
    bid_ask_spread: Optional[float] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert to API-friendly dictionary."""
        return {
            "signal_id": self.signal_id,
            "timestamp": self.timestamp.isoformat(),
            "strategy_id": self.strategy_id,
            "instrument_long": self.instrument_long,
            "instrument_short": self.instrument_short,
            "action": self.action.value,
            "side": self.side.value,
            "predicted_state": self.predicted_state.value,
            "size": self.size,
            "confidence": self.confidence,
            "expected_hold_time": self.expected_hold_time,
            "rationale": self.rationale,
            "model_version": self.model_version,
            "risk_checks_passed": self.risk_checks_passed,
            "predicted_spread": self.predicted_spread,
            "predicted_margin": self.predicted_margin,
            "leap_duration_days": self.leap_duration_days,
            "entry_price": self.entry_price,
            "settle_price": self.settle_price,
            "bid_ask_spread": self.bid_ask_spread,
        }


@dataclass
class PriceBar:
    """OHLCV price bar (1h, 1d, 1w)."""
    instrument_id: str
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float
    vwap: Optional[float] = None


@dataclass
class Spread:
    """Spread value between two instruments."""
    instrument_long: str
    instrument_short: str
    timestamp: datetime
    value: float
    spread_type: str  # "time" or "geo"


@dataclass
class Feature:
    """Single feature value for ML."""
    commodity: str
    contract: str
    feature_name: str
    feature_value: float
    timestamp: datetime
    leap_duration_days: Optional[int] = None


@dataclass
class ModelPrediction:
    """LightGBM model prediction output."""
    commodity: str
    contract: str
    leap_duration_days: int
    predicted_spread: float
    predicted_value: float
    model_version: str
    timestamp: datetime
    r_squared: Optional[float] = None
    mae: Optional[float] = None
    rmse: Optional[float] = None


@dataclass
class BacktestResult:
    """Backtesting metrics for a signal."""
    strategy_id: str
    commodity: str
    start_date: datetime
    end_date: datetime
    total_signals: int
    winning_signals: int
    losing_signals: int
    precision: float  # TP / (TP + FP)
    recall: float  # TP / (TP + FN)
    f1_score: float
    total_pnl: float
    avg_pnl_per_signal: float
    sharpe_ratio: float
    max_drawdown: float


@dataclass
class PnLAttribution:
    """P&L attribution record."""
    attribution_date: datetime
    commodity: str
    product: str
    strategy_id: Optional[str] = None
    mtm_value: float = 0.0
    entry_price: Optional[float] = None
    exit_price: Optional[float] = None
    quantity: float = 0.0
    deal_number: Optional[str] = None
